In [2]:
import numpy as np

In [3]:
mylist = [1,2,3]

In [4]:
type(mylist)

list

In [5]:
np.array(mylist)

array([1, 2, 3])

In [7]:
type(mylist)

list

In [9]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [13]:
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
mymatrix = np.array(mylist)

In [15]:
mymatrix.shape

(3, 3)

In [16]:
mynewmatrix = np.array(mylist)

In [18]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [20]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
type(0.0)

float

In [23]:
type(0.)

float

In [24]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
np.ones((5,5)) + 4 #can perform a transformation on entire matrix

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [27]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [29]:
np.linspace(0,10,20) #gives 20 linearly spaced numebers between 0 and 10

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [30]:
np.eye(5) #creates identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
np.random.rand(1) #gives one random distribution between 0 and 1

array([0.33971213])

In [33]:
np.random.rand(5,5) #five by five array of random numbers

array([[0.45922051, 0.84877881, 0.5424102 , 0.30483317, 0.47110428],
       [0.73344571, 0.79290751, 0.17589464, 0.38034711, 0.94502637],
       [0.16084268, 0.43927929, 0.38563474, 0.04825653, 0.23880945],
       [0.88979593, 0.5614087 , 0.67402547, 0.79685708, 0.55958239],
       [0.28186785, 0.75313236, 0.04640026, 0.37526822, 0.63816214]])

In [34]:
np.random.randn(1) #one number from random normal distribution

array([-2.18055501])

In [35]:
#np.random.normal

In [36]:
np.random.randint(1,100) #set min and max

34

In [37]:
np.random.randint(1,100,10) #min, max, number of numebers

array([37, 78, 18, 25, 79, 23, 80, 44, 37, 63])

In [40]:
np.random.seed(42) #set seed in same cell
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [41]:
arr = np.arange(25)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
ranarr = np.random.randint(0,50,10)

In [44]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [45]:
arr.shape

(25,)

In [46]:
arr.reshape(5,5) #can reshape the array you made as long as the arrangement works

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

NameError: name 'randarr' is not defined

In [48]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [50]:
ranarr.max() #max value of your array

39

In [53]:
ranarr.min() #min value of your array

2

In [55]:
ranarr.argmax() #shows position of max value in matrix

7

In [56]:
ranarr.argmin() #shows position of min value in matrix

9

In [58]:
ranarr.dtype #type that is in array

dtype('int32')

In [59]:
arr = np.arange(0,11)

In [60]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
#bracket indexing and selecting

In [62]:
arr[8]

8

In [64]:
arr[1:5] #up to not uncluding, same as python list slicing

array([1, 2, 3, 4])

In [65]:
arr[:5]

array([0, 1, 2, 3, 4])

In [66]:
#broadcasting

In [67]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [69]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [70]:
#changes are not permanent, would have to reassign to a new variable

In [71]:
arr ** 2 #square it

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [72]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
slice_of_array = arr[0:6]

In [74]:
slice_of_array

array([0, 1, 2, 3, 4, 5])

In [75]:
slice_of_array[:] = 99 #grab everything in slice_of_array and set equal to 99

In [76]:
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [78]:
arr #will also affect original array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [79]:
arr_copy = arr.copy() #can make a copy if you dont want slice to affect original

In [80]:
arr_copy[:] = 10000

In [81]:
arr_copy

array([10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000, 10000])

In [82]:
arr #stays the same

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [83]:
# indexing on a 2 dimensional array

In [84]:
arr_2d  = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [85]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [86]:
arr_2d.shape

(3, 3)

In [87]:
arr_2d[1] #things start at zero in python

array([20, 25, 30])

In [88]:
arr_2d[1][1]

25

In [89]:
arr_2d[1,1]

25

In [90]:
arr_2d[2,2]

45

In [91]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [92]:
#goal is to grab  [10, 15 / 25, 30]

In [93]:
arr_2d[:2] #all the rows not including 2

array([[ 5, 10, 15],
       [20, 25, 30]])

In [95]:
arr_2d[:2,1:] #1: end to get the last two rows

array([[10, 15],
       [25, 30]])

In [96]:
#conditional selection

In [97]:
arr = np.arange(1,11)

In [98]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [104]:
arr > 4 #returns a boolean array

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [105]:
bool_arr = arr > 4 # can set a boolean array

In [101]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [103]:
arr[bool_arr] #can select from arr based on boolean array

array([ 5,  6,  7,  8,  9, 10])

In [106]:
arr[arr>4] #can do it all in one set

array([ 5,  6,  7,  8,  9, 10])

In [107]:
arr[arr == 2]

array([2])

In [108]:
arr[arr <= 6]

array([1, 2, 3, 4, 5, 6])

In [109]:
arr = np.arange(0,10)

In [110]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
arr + arr #can also perform matrix matrix operations

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [114]:
1/arr #will produce output but will just give a warning and show placeholder for infinity

C:\Users\ltemp\anaconda3\envs\pytorchenv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [115]:
arr/arr #nan not a number, warning

C:\Users\ltemp\anaconda3\envs\pytorchenv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [116]:
#universal array functions

In [117]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [118]:
np.log(arr)

C:\Users\ltemp\anaconda3\envs\pytorchenv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [119]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [120]:
#many more in the notebook

In [121]:
#summary stats

In [122]:
arr.sum()

45

In [123]:
arr.mean()

4.5

In [124]:
arr.max()

9

In [126]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [127]:
arr_2d.shape

(3, 4)

In [128]:
arr_2d.sum()

78

In [131]:
arr_2d.sum(axis=0) #axis=0 returns sum across the rows
#produces the sum of each column

array([15, 18, 21, 24])

In [132]:
arr_2d.sum(axis=1) #axis=1 returns sum across the columns
#produces the sum of each row

array([10, 26, 42])